session_name: Tree-sitter-python
windows:
  - window_name: Tree-sitter-python
    layout: main-vertical
    options:
      main-pane-width: 20%
    panes:
      - shell_command:
          - cd ~/Documents/Notes/Projects/tree-sitter-python-tagged
          # - nvim Notes.md ToDo.md
          - open-project
      - shell_command:
          - tmux resizep -y 85%
          - filelist-open "startup_files.txt" "tree-sitter-python-tagged"
        focus: true
      - clear
